bloombergQuoteService:
  cacheTimoutMinutes: 60
yahooCurrencyService:
  cacheTimeoutMinutes: 720

spring:
  data:
    mongodb:
      database: MoneyTrackerV2

google:
    client:
      clientId: ${google.client.clientId}
      clientSecret: ${google.client.clientSecret}
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo
      preferTokenInfo: false

